FROM mcr.microsoft.com/dotnet/aspnet:9.0
LABEL "Project_name"="NopCommerce"
LABEL "Author"="Akhil_Tejas"
RUN useradd -U akhilgc009 -m -d /home/nopcommerce -s /bin/bash
USER akhilgc009
COPY --chown=akhilgc009:akhilgc009 ./published/ nopcommerce/
WORKDIR /nopcommerce
CMD [ "dotnet","Nop.Web.dll", "--url", "http://0.0.0.0:5000"]
EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "Ping","-c","4","http://localhost:5000" ]



