FROM amazoncorretto:17-alpine3.20 
LABEL "Author"="Akhil"
LABEL "Date"="7/7/2024"
RUN wget https://artifactrepoforat225.s3.ap-south-1.amazonaws.com/spring-petclinic-3.4.0-SNAPSHOT.jar
CMD ["java","-jar","spring-petclinic-3.4.0-SNAPSHOT.jar"]