---
apiVersion: v1
kind: Pod
metadata:
  name: nop-pod
  labels:
    app: nop
    env: dev
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: init-container
      image: alpine
      args:
        - sleep
        - 15sec
  containers:
    - name: spc-pod
      image: akhilgc009/nop:0vul
      imagePullPolicy: IfNotPresent
      command: 
        - dotnet Nop.Web.dll --urls="http://0.0.0.0:5000"
      ports:
        - protocol: TCP
          containerPort: 5000
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "250m"
          memory: "250Mi"
      livenessProbe:
        failureThreshold: 3
        tcpSocket:
          port: 5000
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 1
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 120
        periodSeconds: 10
        successThreshold: 2
        tcpSocket:
          port: 5000
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1655
        seccompProfile:
          type: RuntimeDefault
  securityContext:
    seccompProfile:
      type: RuntimeDefault


        
